- .env
- docs/authentication
- e2e/auth.setup.js
- e2e/crm7/caseworker/change-risk.spec.js
- helpers/index.js
- package.json
- yarn.lock
Adds basic documentation and some code clean ups. Code cleanup will continue in next few PRs.
> Adds documentation and cleanup

- e2e/crm7/caseworker/change-risk.spec.js
- e2e/crm7/fixtures/caseworker/index.js
- e2e/crm7/pages/caseworker/all-claims-page.js
- helpers/index.js
Updates Authentication helper function and adds data to fixtures.
> Updates fixtures and helper functions

- Dockerfile
- README.md
- docker-compose.yml
- package.json
- yarn.lock
1. Adds docker file
2. Adds docker compose
3. Updates readMe
> [CRM457-929] Create docker containers for end to end tests

- README.md
- e2e/crm7/pages/provider/your-details.js
- helpers/index.js
Solicitor name is now entered as 2 separate fields. Also I expanded on how to work with the docker compose locally.
> CRM457-1181: Use separate name fields for solicitor

- .circleci/config.yml
- .circleci/pull_image
Add optional working directory env var
To allow other repos to pull repo into
another folder and work from that.
> Add optional working directory env var

- e2e/crm4/pages/provider/primary-quote.js
- helpers/index.js
Here is the provider branch offering new 'town' field passing the E2E tests using this branch: https://app.circleci.com/pipelines/github/ministryofjustice/laa-submit-crime-forms/3010/workflows/0ba046c1-1b6b-44a4-90ff-ad476dac422d/jobs/19027 (It was easier to get tests passing on that branch than this one, cos on that one I could just specify a branch, whereas on this one I'd have to specify an image ID)
> CRM457-1309: Fill in town

- .github/pull_request_template.md
- build_test_local.sh
- docker-compose.local.yml
- docker-compose.yml
- e2e/auth.setup.js
- e2e/crm4/pages/provider/firm-account-number.js
- e2e/crm4/pages/provider/index.js
- e2e/crm4/scenarios/scenario-7.spec.js
- e2e/crm7/pages/provider/firm-account-number.js
- e2e/crm7/pages/provider/index.js
- e2e/crm7/scenarios/scenario-1.spec.js
- helpers/index.js
- run_test_local.sh
Fix breakages to test users (on branch) and docker script improvements
Tests fixed when run against branch [CRM457-1386: improve test users](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/742)
- Amend tests inline with test user changes
- Amend local scripts to clear up and rebuild
- Remove docker-compose version
- Add github PR template
- TOBEREMOVED: point to provider branch (couple of commits need removing before merge
This will need to be approved, and then commits removed and PR merged just after or before [this PR is merged](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/742)
> CRM457-1386: Fix breakages from changes to test users

- e2e/crm7/pages/provider/case-details.js
- e2e/crm7/pages/provider/claim-details.js
- e2e/crm7/pages/provider/defendant-details.js
- e2e/crm7/pages/provider/firm-account-number.js
- e2e/crm7/pages/provider/hearing-details.js
- e2e/crm7/pages/provider/what-are-you-claiming.js
- e2e/crm7/pages/provider/your-details.js
- e2e/crm7/scenarios/scenario-1.spec.js
- helpers/index.js
Rename formData to nsmData
[Came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-1386)
Inline with priorAuthorityData name and
to clearly separate their usage.
> Rename formData to nsmData

- e2e/crm7/pages/caseworker/all-claims.js
- e2e/crm7/scenarios/scenario-1.spec.js
Fixes inline with changes to routes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1474)
> CRM457-1474: Changes inline with nsm home page changes

- e2e/crm7/pages/provider/claim-details.js
Fix inline with addition of wasted costs field to claim details
[Link to wasted costs ticket](https://dsdmoj.atlassian.net/browse/CRM457-1464)
[Related ticket](https://dsdmoj.atlassian.net/browse/CRM457-1501)
https://github.com/ministryofjustice/laa-submit-crime-forms/pull/802
> CRM457-1464: Fix inline with addition of wasted costs field to claim details

- e2e/crm7/pages/provider/hearing-details.js
- e2e/crm7/scenarios/scenario-1.spec.js
Court list is being updated via: https://dsdmoj.atlassian.net/browse/CRM457-1321
[Proof that this change works with the target branch](https://app.circleci.com/pipelines/github/ministryofjustice/laa-submit-crime-forms/3453/workflows/636ab643-ed72-49fe-b261-6de8dda1fc41/jobs/22401)
> CRM457-1321: Use viable court in e2e test

- Dockerfile
- package.json
- yarn.lock
[Update Playwright Docker Image](https://dsdmoj.atlassian.net/browse/CRM457-1680)
> CRM457-1680: Fix Playwright Versioning

- e2e/crm4/scenarios/scenario-7.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1663)
This changes according to a content change PR for CRM4 in Submit app
> CRM457-1663: Content change fix

- docker-compose.yml
Allow Analytics user to be setup
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1630)
> Add new ENV vars

- e2e/crm7/scenarios/scenario-1.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1695)
> CRM457-1695: Update test expectation around firm account number wording

- .env
- e2e/crm7/pages/provider/claim-details.js
Add work completed date 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1697)
> [CRM457-1697] Add work completed date

- .env
- e2e/crm7/scenarios/scenario-1.spec.js
update text in test
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1723)
> Update table values

- e2e/crm7/scenarios/scenario-1.spec.js
update url to get tests passing
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1737)
> [CRM457-1737] Updated URL check or review and adjust screen

- e2e/crm7/scenarios/scenario-1.spec.js
update inline with chnagees in https://github.com/ministryofjustice/laa-assess-crime-forms/pull/638
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1768)
> [CRM457-1768] Update URL (again)

- e2e/crm7/scenarios/scenario-1.spec.js
Changes in line with CRM457-1758
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1758)
Changes to adding a disbursement page
> CRM457-1758: Amendments in line with crm457-1758

- e2e/crm7/scenarios/scenario-1.spec.js
- helpers/index.js
Accommodate inclusion of new question
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1831)
> CRM457-1831: Add office area question

- e2e/crm4/scenarios/scenario-7.spec.js
- e2e/crm7/scenarios/scenario-1.spec.js
Change "firm account" to "firm office account"
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1840)
Inline with content changes for CRM457-1840
see https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1050
> CRM457-1840: Change "firm account" to "firm office account"

- e2e/crm7/scenarios/scenario-1.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1836)
> CRM457-1836: Remove designated area q

- e2e/crm7/pages/provider/hearing-details.js
Explicit designated area question no longer exists
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1841)
> CRM457-1841: Remove redundant question

- e2e/crm7/pages/provider/defendant-details.js
- e2e/crm7/scenarios/scenario-1.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1789)
> CRM457-1789: Fix labels

- e2e/crm7/scenarios/scenario-1.spec.js
Update date format
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1756)
> [CRM457-1756] Update date format

- e2e/crm7/pages/provider/hearing-details.js
Change inline wiuth content tweak
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1875)
> Amendment inline with question content change

- e2e/crm7/pages/provider/contact-details.js
- e2e/crm7/pages/provider/index.js
- e2e/crm7/pages/provider/your-details.js
- e2e/crm7/scenarios/scenario-1.spec.js
- helpers/index.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1867)
> CRM457-1867: Add contact details page

- e2e/crm7/scenarios/scenario-1.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1861)
> CRM457-1861: Change order of NSM questions

- .github/dependabot.yml
Set up combining and weekly-scheduling dependabot PRs to align with how our other repos work.
Remove irrelevant dependabot config
> Dependabot grouping

- docker-compose.yml
Code now expects 2 env vars for file size
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1962)
> CRM457-1962: Change env vars

- e2e/crm7/scenarios/scenario-1.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2015)
> CRM457-2015: Updated provider defendant content

- docker-compose.local.yml
- e2e/crm7/helpers/providerTestStepsHelper.js
- e2e/crm7/scenarios/submit-and-assess-claim/provider.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2388)
Updates content expectations for Work items page
> Crm457-2388: Update tests for NSM Provider: Bulk upload - incomplete work items/ disbursements

- e2e/crm7/helpers/flows/providerFlows.js
- e2e/crm7/scenarios/submit-and-assess-claim/provider.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2391)
> CRM457-2391 xml import and standard input update of add defendant messaging

- e2e/crm7/helpers/caseworkerTestStepsHelper.js
- e2e/crm7/scenarios/submit-and-assess-claim/caseworker.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2525)
> Remove supplemental_claim text

- e2e/crm7/scenarios/submit-a-claim-with-boi/provider.spec.js
- e2e/crm7/scenarios/submit-and-assess-claim/caseworker.spec.js
- e2e/crm7/scenarios/submit-and-assess-claim/provider.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2334)
Update tests that break with new laa crime forms common gem
Below is the result of running tests locally with the new gem and the updated provider and caseworker services:
> CRM457-2334: Align rounding in NSM with caseworker rounding process

- e2e/crm7/scenarios/submit-and-assess-claim/caseworker.spec.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2675)
> Adjust heading to use LAA ref instead of defendent name
